services:
  omt-fe:
    image: registry.digitalocean.com/so-thai/omt-fe:latest
    container_name: omt-fe
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://omt-api.gct.my.idy.id}
    networks:
      - global-network
    restart: unless-stopped

networks:
  global-network:
    external: true
